language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
  matrix:
    - PLONE_VERSION=5.1
matrix:
  fast_finish: true
install:
- sed -ie "s#test-5.1.x#test-$PLONE_VERSION.x#" buildout.cfg
- pip install -U pip
- pip install -r https://raw.githubusercontent.com/plone/buildout.coredev/5.1/requirements.txt
- buildout annotate
- buildout
script:
- bin/test
